openapi: 3.0.0
info:
  title: DigitalAlpha
  version: 1.0.0
servers:
- description: Production
  url: https://dalpha-server-inter-iit.herokuapp.com/api/v1/
paths:
  /search:
    get:
      operationId: searchCompany
      parameters:
      - explode: true
        in: query
        name: name
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResults'
          description: Returns the search result
      summary: Search a company by it's name
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
  /financials:
    get:
      operationId: getFinancials
      parameters:
      - explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Financials'
          description: Returns the company's financials
      summary: Get financials information for a company in the time range specified
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
  /{attributeId}:
    get:
      operationId: getAttribute
      parameters:
      - explode: false
        in: path
        name: attributeId
        required: true
        schema:
          enum:
          - returnonequity
          - netinventory
          - liabilities
          - financialleverage
          - operatingincome
          - nonoperatingincomeexpense
          - depreciation
          - incometaxesextraordinaryitemsnoncontrollinginterest
          - netincomeloss
          type: string
        style: simple
      - explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: start
        required: false
        schema:
          type: number
        style: form
      - explode: true
        in: query
        name: end
        required: false
        schema:
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attributes'
          description: Returns the company's attribute in the specified interval
      summary: Get attribute information for a company in the time range specified
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
  /download.csv:
    get:
      operationId: generateCSV
      parameters:
      - explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          description: 'Download CSV file'
          content:
            text/csv:
              schema:
                type: string
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
  /announcements:
    get:
      operationId: getAnnouncements
      parameters:
      - explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          description: 'Get Announcements of a company'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Announcements'
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
  /fraud:
    get:
      operationId: getFraud
      parameters:
      - explode: true
        in: query
        name: id
        required: true
        schema:
          type: string
        style: form
      responses:
        200:
          description: 'Get detected fraud percentage'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fraud'
      x-swagger-router-controller: Default
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    CompanyProfile:
      example:
        ticker: ticker
        name: name
      properties:
        ticker:
          description: Stock ticker of company
          type: string
        name:
          description: Name of Company
          type: string
      type: object
    SearchResults:
      example:
        exact: true
        results:
        - ticker: ticker
          name: name
        - ticker: ticker
          name: name
      properties:
        exact:
          description: Whether the result is an exact match or not
          type: boolean
        results:
          items:
            $ref: '#/components/schemas/CompanyProfile'
          type: array
      type: object
    Attribute:
      example:
        quat:
        - ""
        - ""
        year: 0.8008281904610115
        hasQuat: true
        value: 6.027456183070403
      properties:
        year:
          type: number
        quat:
          items:
            oneOf:
            - type: number
            - type: boolean
          type: array
      type: object
    Attributes:
      items:
        $ref: '#/components/schemas/Attribute'
      type: array
    Financials:
      example:
        financialData1:
          from: '2019-10-01T00:00:00.000Z'
          to: "2020-09-30T00:00:00.000Z"
          value:
            metric1: 102
            metric2: 18
        financialData2:
          date: '2019-10-01T00:00:00.000Z'
          value:
            metric1: 102
            metric2: 18
      type: object
    Announcements:
      items:
        type: object
        properties:
          date:
            type: string
            format: date
          positive:
            type: number
          negative:
            type: number
          text:
            type: string
      example: 
      - date: '2019-10-01T00:00:00.000Z'
        positive: 0.504
        negative: 0.206
        text: 'This is an announcement\nCompany ABC'
      - date: '2019-10-01T00:00:00.000Z'
        positive: 0.4
        negative: 0.26
        text: 'This is another announcement\nCompany ABC'
      type: array
    Fraud:
      type: object
      properties:
        fraud:
          type: number
      example:
        fraud: 42.89
